version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: diario_frontend
    restart: always
    ports:
      - "3550:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL:-https://dagendang.com}
      - TZ=America/Santo_Domingo
      - NODE_ENV=production
