"""add image_url and status and enum values to article

Revision ID: 1d141c05bc8a
Revises: edf20d44abf3
Create Date: 2026-03-11 22:56:26.202373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d141c05bc8a'
down_revision: Union[str, Sequence[str], None] = 'edf20d44abf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'status')
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###
