"""add gemini_image_model to user

Revision ID: 2ee80e1607aa
Revises: a7c572705629
Create Date: 2026-03-13 22:09:24.109948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee80e1607aa'
down_revision: Union[str, Sequence[str], None] = 'a7c572705629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gemini_image_model', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gemini_image_model')
    # ### end Alembic commands ###
