"""add is_premium to articles

Revision ID: 6602d15f2f82
Revises: c5a676cb30bd
Create Date: 2026-03-12 00:26:29.672463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6602d15f2f82'
down_revision: Union[str, Sequence[str], None] = 'c5a676cb30bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('is_premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'is_premium')
    # ### end Alembic commands ###
