"""restore_advertisements

Revision ID: 8b37a6eda002
Revises: 9429a2155e8b
Create Date: 2026-03-13 12:03:14.532074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b37a6eda002'
down_revision: Union[str, Sequence[str], None] = '9429a2155e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rotation_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisements_position'), 'advertisements', ['position'], unique=False)
    op.create_index(op.f('ix_advertisements_title'), 'advertisements', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisements_title'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_position'), table_name='advertisements')
    op.drop_table('advertisements')
    # ### end Alembic commands ###
