"""add_categories

Revision ID: 9429a2155e8b
Revises: fec94976f4cd
Create Date: 2026-03-13 11:55:41.302865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9429a2155e8b'
down_revision: Union[str, Sequence[str], None] = 'fec94976f4cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.drop_index(op.f('ix_advertisements_position'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_title'), table_name='advertisements')
    op.drop_table('advertisements')
    op.alter_column('articles', 'type',
               existing_type=postgresql.ENUM('opinion', 'editorial', 'mercados', 'finanzas', 'empresas', 'nacional', 'economia', name='articletype'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('opinion', 'editorial', 'mercados', 'finanzas', 'empresas', 'nacional', 'economia', name='articletype'),
               existing_nullable=False)
    op.create_table('advertisements',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rotation_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('advertisements_pkey'))
    )
    op.create_index(op.f('ix_advertisements_title'), 'advertisements', ['title'], unique=False)
    op.create_index(op.f('ix_advertisements_position'), 'advertisements', ['position'], unique=False)
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
