"""create_advertisements_table

Revision ID: a1e080c43ccd
Revises: 245f34d03f92
Create Date: 2026-03-11 22:29:11.066497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e080c43ccd'
down_revision: Union[str, Sequence[str], None] = '245f34d03f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisements_position'), 'advertisements', ['position'], unique=False)
    op.create_index(op.f('ix_advertisements_title'), 'advertisements', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisements_title'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_position'), table_name='advertisements')
    op.drop_table('advertisements')
    # ### end Alembic commands ###
