"""Add backup configuration to user

Revision ID: a7c572705629
Revises: 8b37a6eda002
Create Date: 2026-03-13 16:12:23.934661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c572705629'
down_revision: Union[str, Sequence[str], None] = '8b37a6eda002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('backup_limit_gb', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('backup_frequency_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'backup_frequency_hours')
    op.drop_column('users', 'backup_limit_gb')
    # ### end Alembic commands ###
