"""Add glp and gas_natural to fuel prices

Revision ID: c5a676cb30bd
Revises: 1d141c05bc8a
Create Date: 2026-03-11 23:12:14.953825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5a676cb30bd'
down_revision: Union[str, Sequence[str], None] = '1d141c05bc8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fuel_prices', sa.Column('glp', sa.Float(), server_default='132.60', nullable=False))
    op.add_column('fuel_prices', sa.Column('gas_natural', sa.Float(), server_default='43.90', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fuel_prices', 'gas_natural')
    op.drop_column('fuel_prices', 'glp')
    # ### end Alembic commands ###
