"""add_per_article_ad_fields

Revision ID: c752fcc81061
Revises: a1e080c43ccd
Create Date: 2026-03-12 13:05:08.084179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c752fcc81061'
down_revision: Union[str, Sequence[str], None] = 'a1e080c43ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('ad_image_url', sa.String(length=500), nullable=True))
    op.add_column('articles', sa.Column('ad_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'ad_link')
    op.drop_column('articles', 'ad_image_url')
    # ### end Alembic commands ###
