"""add_economia_to_article_type

Revision ID: dacdf6380f8f
Revises: c752fcc81061
Create Date: 2026-03-12 19:04:58.949951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacdf6380f8f'
down_revision: Union[str, Sequence[str], None] = 'c752fcc81061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE articletype ADD VALUE 'economia'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
