"""add_ad_rotation_seconds

Revision ID: fec94976f4cd
Revises: 0de4fe38a0f9
Create Date: 2026-03-12 21:43:57.630065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec94976f4cd'
down_revision: Union[str, Sequence[str], None] = '0de4fe38a0f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('rotation_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'rotation_seconds')
    # ### end Alembic commands ###
